### PR TITLE
Added application id.

### PR DESCRIPTION
**Pull request by SaaldjorMike**
Also:
Added udp+tcp src and dst ports.

screen shot 2016-09-17 at 15 58 26

### CODE REVIEW

**Comment by SaaldjorMike** [comment]
I did sign the CLA, but looks like the PR did not get updated.

**Comment by jorritfolmer** [comment]
Hi thanks for taking the time to submit this PR. Can you provide any reference to fields 180, 181, 182, 183? I couldn't find any mention of it in the Cisco docs or RFC. What device emits flow records with these fields? It would also be really helpful if you can provide same sample traffic in .pcap.

**Comment by SaaldjorMike** [comment]
The device I'm using is a Cisco 4500-X which supports "Flexible NetFlow".
Search for `show flow exporter export-ids netflow-v9` in the following page:
https://www.cisco.com/c/en/us/td/docs/ios/fnetflow/command/reference/fnf_book/fnf_02.html

For the application id, there is a few pages that mentions it.
E.g. http://docwiki.cisco.com/wiki/AVC-Export:Monitoring

.pcap file with sample traffic:
[flowdump.pcap.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/480915/flowdump.pcap.zip)

**Comment by jorritfolmer** [comment]
Awesome!

**Pull request merged**
