### PR TITLE
Update with new Event APIs

### PR DESCRIPTION
**Pull request by suyograo**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by ph** [comment]
LGTM,

**Comment by jorritfolmer** [comment]
LGTM too. Where can I find more info on the new event API? Curious if it'll help with #9 .

**Comment by ph** [comment]
@jorritfolmer Thanks for the follow up.

I suggest you check the meta issue and the referenced issues in the description.

See: https://github.com/elastic/logstash/issues/5227

**Comment by jorritfolmer** [comment]
Ah ok I think I understand now. The only place where the new event api is relevant, for this codec, is in the rspec tests. The rest of the code in this codec doesn't use the new event API because it gets passed a `payload` object through `decode`, for example from the logstash_input_udp plugin.

**Pull request merged**
