### PR TITLE
Fix exception when parsing fields with a mac address

### PR DESCRIPTION
**Pull request by jorritfolmer**
Fixes issue #19 and #26.

This PR also contains a test. However this is not yet working because I don't know how to process the 2 packets in the right order, in rspec.
The test depends on the netflow9_test_macaddr_tpl.dat being decoded first.
After that the netflow9_test_macaddr_data.dat should properly decode into json containing a mac address, which the expect() part checks for.
The data template and actual data are seperate because that is the way the netflow exporter works, in this case. The tests that were already included have both the data template and the actual data in 1 packet, simplyfing testing.

### CODE REVIEW

**Comment by jorritfolmer** [comment]
Ok the test now works with the 2 .dat files in the proper order.

**Comment by jorritfolmer** [comment]
CLA signed

**Comment by suyograo** [comment]
@jorritfolmer Sorry for the delays here. Can you please rebase your PRs and I will merge them ASAP.

**Comment by jorritfolmer** [comment]
Ok rebase done

**Pull request closed without merging**
