### PR TITLE
Auto Skip feature added

### PR DESCRIPTION
**Pull request by propulkit**
Generally, developers facing issue with unsupported fields in Netflow. By setting auto_skip to true all unsupported fields will be skipped automatically without defining each field as skip in Netflow.yaml definitions file.

I believe it help user to develop thing faster with netflow codec.

Thanks,
Pulkit Agrawal

### CODE REVIEW

**Comment by propulkit** [comment]
Help me with CLA. I would like to add this feature in plugin to help community.

**Comment by purbon** [comment]
@propulkit thanks a lot for your time, to sign the CLA you can go https://www.elastic.co/contributor-agreement. Please use the same email as the one used in your PR, this will simplify the necessary checks.

**Comment by purbon** [comment]
@propulkit it would be required to add test, to this feature gets tested and the quality assured. thanks a lot for your time and contribution.

**Comment by propulkit** [comment]
Thanks @purbon 
I got CLA signed. Let me see what it will take to put Jenkins test.

**Comment by purbon** [comment]
@propulkit awesome, I can help you with rspec super powers :+1:

**Comment by propulkit** [comment]
@purbon Your help will be highly appreciated :+1:

**Comment by propulkit** [comment]
@purbon Can you please test the same?
Thanks,
Pulkit Agrawal

**Comment by karmi** [comment]
Hi @propulkit, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-codec-netflow/pull/15.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by propulkit** [comment]
@karmi I really don't know why such confusion occur. I think I have used the same Email-ID for CLA as of Github. I made two commits first commit was without any author information but I correct that in my second commit. I think that cause this mismatch for first commit. I have made my Github email public so it can be verified with email in CLA.

**Comment by jorritfolmer** [comment]
Ok regarding the tests: I think I can hack together a Netflow packet that contains unsupported fields, so we can use that to:

* test if a warning message "Unsupported field" is returned  with `auto_skip` disabled
* test if:
    * the parameter is accepted
    * no exception is raised 
    * no log message is returned if `auto_skip` is enabled

I think expecting specific log messages goes something like `expect(decode.size).to receive(:warming).with("Unsupported field")` when auto_skip disabled and the above Netflow packet in a .dat file.

However, I have no idea how to:

* test whether `auto_skip` is accepted as parameter
* pass a parameter like `auto_skip` to Logstash through rspec.

@purbon could you assist?

**Comment by karmi** [comment]
Hi @propulkit, the e-mail doesn't have to be public, just attached to your Github profile --  but in any case, it passes now!

**Comment by propulkit** [comment]
Thanks @karmi

**Comment by tpnoonan** [comment]
How do i use the auto_skip parameter?  Passed in to logstash at startup or a part of my netflow conf file?  Thanks, Tommy

**Comment by propulkit** [comment]
@tpnoonan ( Tommy ) It is added as part of netflow config file.

**Comment by tpnoonan** [comment]
@propulkit - Thanks for the response.  I've given it a go in multiple locations in my netflow configuration to no avail.  Any chance you can share an example of its use?

**Comment by propulkit** [comment]
@tpnoonan  , make sure you are using right repository https://github.com/propulkit/logstash-codec-netflow as changes are not yet merged.

**Comment by tpnoonan** [comment]
I am running the latest 2.1 on logstash 2.3.2 due to the IPFIX capabilities.  When will this feature be merged?  Thanks!

**Comment by jorritfolmer** [comment]
This feature will be merged as soon as there in an rspec test written for it, that passes. Reason: test driven development: https://www.elastic.co/guide/en/logstash/current/contributing-patch-plugin.html#_test_driven_development

I'm willing to do help create these test(s) and outlined my ideas about it in https://github.com/logstash-plugins/logstash-codec-netflow/pull/15#issuecomment-217470711, however I don't have a black-belt in rspec, yet. So assistance greatly appreciated!

**Comment by rwaweber** [comment]
Sorry to dust off this PR after roughly a year and a half, this would be a pretty neat feature in my use case of having to ingest handfuls of proprietary, often empty netflow templates.

I'd be happy to pick up where @propulkit left off and try to add some rspec tests in another PR. @jorritfolmer thoughts?

**Comment by jorritfolmer** [comment]
Yes I think this autoskip feature is neat too!
I think you can best create a new PR based on the current master branch.

**Comment by propulkit** [comment]
Go ahead.

**Comment by jorritfolmer** [comment]
Closing. Feel free to reopen if needed.

**Pull request closed without merging**
