### PR TITLE
add procera enterprise values as per 15.1 product guide

### PR DESCRIPTION
**Pull request by abeeson**
As per the commit message, adding the enterprise values for Procera/NetIntact/Sandvine, specifically the Procera 15.1 version IPFIX values.

If there are more in 16/17 i'll add them once we upgrade to that version and i get access to those guides.

### CODE REVIEW

**Comment by abeeson** [comment]
CLA should be signed now.

**Comment by abeeson** [comment]
I didn't add notes to the changelog or bump the version, let me know if you'd like me to submit that as well as part of the PR.

**Comment by jorritfolmer** [comment]
Hi thanks for the work! Do you happen to have a small pcap to test this? Mostly aimed at making sure that support for Procera keeps working in the future with our rspec tests we run on every commit/release.

**Comment by abeeson** [comment]
Sure do, you can find a pcap here: https://www.dropbox.com/s/jglcpc8gnyv3bbq/procera%20IPFIX%20no%20users.pcapng?dl=0

It contains 2 template sends, and 3 different flow packets with a few sessions in them. Its from our secondary host however, so some of the fields are blank, as i've specifically exported non user data.

It should work for validation though, and the fields are still present, just empty.

If that is no good let me know and i'll see what else i can produce.

**Comment by jorritfolmer** [comment]
Merged

**Pull request closed without merging**
