### PR TITLE
Fix for correctly decoding flows from multple exporters

### PR DESCRIPTION
**Pull request by jorritfolmer**
This is a duplicate of PR #16, but with tests added.
Without the fix, the test fails to decode all netflow data:

````
    Failure/Error: expect(decode.size).to eq(8)
       
       expected: 8
            got: 1
````

With the fix, both data from softflowd and nprobe are decoded:

````
Finished in 4.32 seconds (files took 4.12 seconds to load)
6 examples, 0 failures

Randomized with seed 51877
````

### CODE REVIEW

**Comment by jorritfolmer** [comment]
CLA signed

**Comment by suyograo** [comment]
@jorritfolmer Sorry for the delays here. Can you please rebase your PRs and I will merge them ASAP. Also, would you be interested in maintaining this plugin and we can give you commit access?

**Comment by jorritfolmer** [comment]
Ok rebase done.
Yes I would be interested in maintaining this plugin!

**Comment by jsvd** [comment]
Thanks @jorritfolmer :)

**Pull request closed without merging**
