### PR TITLE
Support for Netflow v9 Cisco ASA fields

### PR DESCRIPTION
**Pull request by jorritfolmer**
Added fields to netflow.yaml based on:

1) http://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/guide/asa_netflow.html
2) a .pcap file from an actual ASA thanks to @hkshirish

Closes issue #20 and likely helps in issue #21.

### CODE REVIEW

**Comment by jorritfolmer** [comment]
I signed the CLA on october 26th 2015, using the same email as my commits and login here. Help?

**Comment by ssi0202** [comment]
has these changes been implemented in the code i can download from elastic.co' site? sorry i don't know what a pull request is :/

**Comment by jorritfolmer** [comment]
Hi Simon you could try downloading the modifications from [this Github url](https://patch-diff.githubusercontent.com/raw/logstash-plugins/logstash-codec-netflow/pull/24.patch) an applying them in the directory that contains your logstash-codec-netflow by running `patch -p1 < 24.path`.

**Comment by ssi0202** [comment]
hi jorrit,

i really appriciate you getting back to me.

is there a specific path that it expects logstash-2.2.2 to be located when
i execute it? or are these patches for another logstash version

for example, with patch 2,  i can find a file named
"logstash-codec-netflow-2.0.3-gemspec" is this the file located in
/opt/logstash/vendor/bundle/1.9/specifications/

best regards


2016-02-18 9:56 GMT+01:00 Jorrit Folmer <notifications@github.com>:

> Hi Simon you could try downloading the modifications from this Github url
> <https://patch-diff.githubusercontent.com/raw/logstash-plugins/logstash-codec-netflow/pull/24.patch>
> an applying them in the directory that contains your logstash-codec-netflow
> by running patch -p1 < 24.path.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logstash-plugins/logstash-codec-netflow/pull/24#issuecomment-185605863>
> .
>



-- 
Simon Simonsen | Nordvestpassagen 79 |
8200 Århus N | Tlf. 20810408

**Comment by jorritfolmer** [comment]
I can only tell you that for my logstash-1.5.5, everything for the 
logstash-codec-netflow is located here on my test-vm:

/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-1.0.0

If the patch complains about some missing 
lostash-codec-netflow-2.0.3-something file, I wouldn't worry too much 
about it,
unless it makes the codec fail of course.

Attached in the .tar.gz is a copy op the logstash-codec-netflow and 
logstash-input-udp that I've been using since august 2015.
Note however I'm running logstash-1.5.5, so you may need to downgrade to 
get it to work.
Untar it in /opt/logstash/vendor/bundle/jruby/1.9/gems/ and you should 
be good to go. This has all the other stuff that hasn't been merged yet 
in it, so I really hope this works for you. On logstash-1.5.5, that is :)

This is the accompanying config that I use:

input {
     udp {
       port => 2055
       codec => netflow {
         versions => [5,9,10]
       }
     }
}

output {
   file {
     codec => "json"
     path => "/var/log/netflow/netflow.json"
   }
}

I have it write to json so I can collect it with Splunk. You'll probably 
output it to ES.

regards,
	Jorrit

**Comment by ssi0202** [comment]
thanks again!

could you send the tar.gz file to this address gmail rips them out - no
matter what you do.

ssi@danskecommodities.com

2016-02-18 13:06 GMT+01:00 Jorrit Folmer <notifications@github.com>:

> I can only tell you that for my logstash-1.5.5, everything for the
> logstash-codec-netflow is located here on my test-vm:
>
> /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-1.0.0
>
> If the patch complains about some missing
> lostash-codec-netflow-2.0.3-something file, I wouldn't worry too much
> about it,
> unless it makes the codec fail of course.
>
> Attached in the .tar.gz is a copy op the logstash-codec-netflow and
> logstash-input-udp that I've been using since august 2015.
> Note however I'm running logstash-1.5.5, so you may need to downgrade to
> get it to work.
> Untar it in /opt/logstash/vendor/bundle/jruby/1.9/gems/ and you should
> be good to go. This has all the other stuff that hasn't been merged yet
> in it, so I really hope this works for you. On logstash-1.5.5, that is :)
>
> This is the accompanying config that I use:
>
> input {
> udp {
> port => 2055
> codec => netflow {
> versions => [5,9,10]
> }
> }
> }
>
> output {
> file {
> codec => "json"
> path => "/var/log/netflow/netflow.json"
> }
> }
>
> I have it write to json so I can collect it with Splunk. You'll probably
> output it to ES.
>
> regards,
> Jorrit
>
> On 18-02-16 11:19, ssi0202 wrote:
> > hi jorrit,
> >
> > i really appriciate you getting back to me.
> >
> > is there a specific path that it expects logstash-2.2.2 to be located
> when
> > i execute it? or are these patches for another logstash version
> >
> > for example, with patch 2, i can find a file named
> > "logstash-codec-netflow-2.0.3-gemspec" is this the file located in
> > /opt/logstash/vendor/bundle/1.9/specifications/
> >
> > best regards
> >
> >
> > 2016-02-18 9:56 GMT+01:00 Jorrit Folmer <notifications@github.com>:
> >
> > > Hi Simon you could try downloading the modifications from this Github
> url
> > >
> > <
> https://patch-diff.githubusercontent.com/raw/logstash-plugins/logstash-codec-netflow/pull/24.patch
> >
> > > an applying them in the directory that contains your
> > logstash-codec-netflow
> > > by running patch -p1 < 24.path.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <
> https://github.com/logstash-plugins/logstash-codec-netflow/pull/24#issuecomment-185605863
> >
> > > .
> > >
> >
> >
> >
> > --
> > Simon Simonsen | Nordvestpassagen 79 |
> > 8200 Århus N | Tlf. 20810408
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/logstash-plugins/logstash-codec-netflow/pull/24#issuecomment-185640715
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logstash-plugins/logstash-codec-netflow/pull/24#issuecomment-185687031>
> .
>



-- 
Simon Simonsen | Nordvestpassagen 79 |
8200 Århus N | Tlf. 20810408

**Comment by ssi0202** [comment]
thanks for the heads up

**Comment by suyograo** [comment]
@jorritfolmer Sorry for the delays here. Can you please rebase your PRs and I will merge them ASAP.

**Comment by suyograo** [comment]
@jorritfolmer Sorry for the delays here. Can you please rebase your PRs and I will merge them ASAP.

**Comment by jorritfolmer** [comment]
Ok rebase done

**Comment by jsvd** [comment]
hi @jorritfolmer I merged #23 which makes this one break again, would mind another quick rebase so I can merge this now?

**Comment by jorritfolmer** [comment]
Yes done

**Pull request closed without merging**
